### ISSUE TITLE
helios-solo container fails to start

### ISSUE THREAD

**Issue by marko-jovicic** [spotify/helios#1116] opened 2017-04-25 16:01 UTC
First problem is nmcli which I changed according to #663 issue. After that docker container fails to start with following error:

```
2017/04/25 15:56:08 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e27652122e8b2ae
100   387  100   247  100   140    193    109  0:00:01  0:00:01 --:--:--   193
{"action":"set","node":{"key":"/skydns/config","value":"{\"dns_addr\":\"0.0.0.0:5353\", \"ttl\":3600, \"nameservers\": [\"192.168.0.96:53\", \"192.168.180.96:53\", \"192.168.0.69:53\"], \"domain\":\"local.\"}","modifiedIndex":3,"createdIndex":3}}
+ break
+ curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/local/solo -d 'value={"host":"172.17.0.1"}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151  100   124  100    27  56724  12351 --:--:-- --:--:-- --:--:-- 62000
{"action":"set","node":{"key":"/skydns/local/solo","value":"{\"host\":\"172.17.0.1\"}","modifiedIndex":4,"createdIndex":4}}
+ unbound
+ skydns
[1493135768] unbound[29:0] error: can't bind socket: Cannot assign requested address
[1493135768] unbound[29:0] debug: failed address ::1 port 8953
[1493135768] unbound[29:0] error: cannot open control interface ::1 8953
[1493135768] unbound[29:0] fatal error: could not open ports
```

**Comment by marko-jovicic** [comment] 2017-04-25 16:02
I am using Ubuntu 16.04.2 LTS. Docker version is:
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by marko-jovicic** [comment] 2017-04-28 10:59
It doesn't work with latest docker engine. I've downgraded version of docker to: 1.13.1-0~ubuntu-xenial

**Comment by mattnworb** [comment] 2017-04-28 15:51
seems like something worth looking into if it happens reliably on 17.04

**Comment by davidxia** [comment] 2017-05-02 19:43
This is the cause. https://github.com/boot2docker/boot2docker/issues/1257

**Comment by mattnworb** [comment] 2017-05-02 19:56
Nice find, but I am confused - how does boot2docker enter the picture when running the helios-solo image on docker 17.04.0-ce? The original problem report was using docker natively on Ubuntu 16.04.

**Comment by davidxia** [comment] 2017-05-02 19:59
Oh, I misread this issue. I'll need to look into this more.

**Comment by davidxia** [comment] 2017-05-03 00:59
This is a [bug in docker 17.04](https://github.com/moby/moby/issues/32433) which should be fixed in 17.05.

**Comment by davidxia** [comment] 2017-05-03 01:00
https://github.com/moby/moby/issues/32433

**Comment by mattnworb** [comment] 2017-05-03 13:26
Ouch.

The [unbound config has `interface: ::0`](https://github.com/spotify/helios/blob/5573fd28c071cebebc1a78d9daff017f3101c4c6/solo/base/unbound-skydns.conf#L3) - do we even need unbound to listen on an IPv6 interface in addition to `0.0.0.0`? 

It is possible for people to set up the docker daemon to have IPv6 disabled so it is probably not safe for helios-solo to assume it can listen on that address, especially if there is no real functional need for it.

**Closed** 2017-05-03 17:38 UTC
Labels: bug, help wanted
